#Application URL
url = https://opensource-demo.orangehrmlive.com/web/index.php/auth/login

#browser Configuration
browser = Chrome

#Credentials
Uusername = admin
password = admin123


#implicitWait (in seconds)
implicitWait = 10